### ISSUE TITLE
Home screen - reduce size of thumbnails - order of content

### ISSUE THREAD

**Issue by lottebelice** [linkedtv/editortool#17]
When I log in and go to the home screen, I see an overview of TKK videos. To me, it is a bit unclear what the sorting order is and since the thumbs are so big it's hard to get a grasp of what's in there. I suggest the following:
- Show at the top how many videos are in that specific part of the ET (in other words: leave the RBB videos out of this :)).
- Show how they are ordered, or even better, allow various ordering possibilities (e.g. title, date of airing, and in a later stage maybe filter on curatorial status).
- Make the thumbs half the current size, it doesn't add much imho to have them this big.

@nicorbb: do you agree?

**Comment by nicorbb** [comment]
erm, well....
- the order of videos is indeed totally unclear. I don't require multiple ordering options, especially because the title always includes the air date, so that these would not be different, but thinking long-term or generic Lotte's suggestions absolutely make sense
- I don't see S&V thumbs, so I'm happy in this respect
- thumbnails half the size would be absolutely enough
